// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"meli.quasarfire/src/provider"
)

// Injectors from wire.go:

func Wire() *provider.Server {
	topSecretService := provider.ProvideService()
	topSecretHandler := provider.ProvideHandler(topSecretService)
	server := provider.ProvideServer(topSecretHandler)
	return server
}
